

Promise.reject({ toSource() { throw "another error"; } });
